version: "3"

services:
  php:
    image: hindsedrati/php
    volumes:
      - ./app:/var/www/html
      - ./php/vhosts:/etc/apache2/sites-enabled
    ports:
      - "8000:80"
    depends_on:
      - composer

  composer:
    image: hindsedrati/composer
    volumes:
      - ./app:/app
    command: install --optimize-autoloader
    restart: "no"

networks:
  default:
    external:
      name: bdd-network